-- ============================================================
-- Group B (C端交易与营销组) 建表脚本
-- 数据库: Oracle 18c
-- 注意: 请先执行项目设计文档中完整的建表脚本后再按需创建
-- ============================================================

-- 1. Crm_MemberLevels - 会员等级定义
CREATE TABLE Crm_MemberLevels (
    MemberLevelId   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LevelName       VARCHAR2(50)   NOT NULL,    -- 普通/银卡/金卡/钻石
    MinSpent        NUMBER(10,2)   NOT NULL,    -- 该等级最低消费门槛
    DiscountRate    NUMBER(4,3)    DEFAULT 1,   -- 折扣率 0.95=95折
    PointsMultiplier NUMBER         DEFAULT 1,   -- 积分倍率
    CONSTRAINT UQ_MemberLevel_MinSpent UNIQUE (MinSpent),
    CONSTRAINT CK_MemberLevel_MinSpent CHECK (MinSpent >= 0),
    CONSTRAINT CK_MemberLevel_Discount CHECK (DiscountRate > 0 AND DiscountRate <= 1),
    CONSTRAINT CK_MemberLevel_Points CHECK (PointsMultiplier >= 1)
);

-- 1.1 Crm_Promoters - 团长分销信息
CREATE TABLE Crm_Promoters (
    PromoterId         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PromoterName       VARCHAR2(50)   NOT NULL,
    Phone              VARCHAR2(20)   NOT NULL,
    BaseCommissionRate NUMBER(5,2)    DEFAULT 0,
    InviteCode         VARCHAR2(50)   NOT NULL UNIQUE,
    CurrentBalance     NUMBER(10,2)   DEFAULT 0,
    PendingBalance     NUMBER(10,2)   DEFAULT 0,
    TotalSales         NUMBER(12,2)   DEFAULT 0,
    TotalOrderCount    NUMBER         DEFAULT 0,
    CreatedAt          DATE           DEFAULT SYSDATE,
    UpdatedAt          DATE
);

-- 2. Crm_Customers - 消费者
CREATE TABLE Crm_Customers (
    CustomerId      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OpenId          VARCHAR2(100),
    CustomerName    VARCHAR2(100)  NOT NULL,
    Phone           VARCHAR2(20)   NOT NULL,
    Email           VARCHAR2(100),
    PasswordHash    VARCHAR2(255)  NOT NULL,
    PromoterId      NUMBER,                       -- 所属团长ID
    MemberLevelId   NUMBER DEFAULT 1,
    TotalSpent      NUMBER(10,2)   DEFAULT 0,     -- 累计消费
    Points          NUMBER         DEFAULT 0,     -- 当前积分
    GrowthValue     NUMBER         DEFAULT 0,
    BindExpireTime  DATE,
    CreatedAt       DATE           DEFAULT SYSDATE,
    UpdatedAt       DATE,
    CONSTRAINT UQ_Customer_Phone UNIQUE (Phone),
    CONSTRAINT FK_Customer_Promoter FOREIGN KEY (PromoterId) REFERENCES Crm_Promoters(PromoterId),
    CONSTRAINT UQ_Customer_OpenId UNIQUE (OpenId),
    CONSTRAINT FK_Customer_Level    FOREIGN KEY (MemberLevelId) REFERENCES Crm_MemberLevels(MemberLevelId)
);

-- 3. Crm_UserAddresses - 收货地址
CREATE TABLE Crm_UserAddresses (
    AddressId       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerId      NUMBER         NOT NULL,
    ReceiverName    VARCHAR2(50)   NOT NULL,
    Phone           VARCHAR2(20)   NOT NULL,
    Province        VARCHAR2(50),
    City            VARCHAR2(50),
    District        VARCHAR2(50),
    DetailAddress   VARCHAR2(200),
    IsDefault       NUMBER(1)      DEFAULT 0,
    CreatedAt       DATE           DEFAULT SYSDATE,
    CONSTRAINT FK_Address_Customer FOREIGN KEY (CustomerId) REFERENCES Crm_Customers(CustomerId),
    CONSTRAINT CK_Address_IsDefault CHECK (IsDefault IN (0, 1))
);

-- 同一消费者最多只能有一条 IsDefault=1 的地址；非默认地址不参与唯一约束。
CREATE UNIQUE INDEX UQ_Address_OneDefault
    ON Crm_UserAddresses (
        CASE WHEN IsDefault = 1 THEN CustomerId END
    );

CREATE INDEX IX_Address_Customer
    ON Crm_UserAddresses (CustomerId, IsDefault);

-- 4. Mkt_Coupons - 优惠券模板
CREATE TABLE Mkt_Coupons (
    CouponId         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CouponName       VARCHAR2(100)  NOT NULL,
    MinOrderAmount   NUMBER(10,2)   DEFAULT 0,
    DiscountAmount   NUMBER(10,2)   NOT NULL,
    TotalQuantity    NUMBER         NOT NULL,
    RemainingQuantity NUMBER        NOT NULL,
    StartTime        DATE           NOT NULL,
    EndTime          DATE           NOT NULL,
    Status           NUMBER(1)      DEFAULT 1,   -- 0=停用 1=启用
    CONSTRAINT CK_Coupon_Amount CHECK (
        MinOrderAmount >= 0 AND DiscountAmount > 0
    ),
    CONSTRAINT CK_Coupon_Quantity CHECK (
        TotalQuantity >= 0
        AND RemainingQuantity >= 0
        AND RemainingQuantity <= TotalQuantity
    ),
    CONSTRAINT CK_Coupon_Time CHECK (EndTime > StartTime),
    CONSTRAINT CK_Coupon_Status CHECK (Status IN (0, 1))
);

-- 5. Mkt_CouponRecords - 用户领券/用券记录
CREATE TABLE Mkt_CouponRecords (
    RecordId        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CouponId        NUMBER         NOT NULL,
    CustomerId      NUMBER         NOT NULL,
    OrderId         NUMBER,                       -- 核销订单
    Status          NUMBER(1)      DEFAULT 0,     -- 0=未用 1=已用 2=过期
    UsedAt          DATE,
    CreatedAt       DATE           DEFAULT SYSDATE,
    CONSTRAINT FK_CouponRec_Coupon   FOREIGN KEY (CouponId) REFERENCES Mkt_Coupons(CouponId),
    CONSTRAINT FK_CouponRec_Customer FOREIGN KEY (CustomerId) REFERENCES Crm_Customers(CustomerId),
    CONSTRAINT UQ_CouponRec_Customer UNIQUE (CouponId, CustomerId),
    CONSTRAINT CK_CouponRec_Status CHECK (Status IN (0, 1, 2))
);

CREATE INDEX IX_CouponRec_CustomerStatus
    ON Mkt_CouponRecords (CustomerId, Status);

-- 6. Crm_PointLogs - 积分流水 (每笔必记)
CREATE TABLE Crm_PointLogs (
    PointLogId      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerId      NUMBER         NOT NULL,
    ChangeAmount    NUMBER         NOT NULL,      -- 正=获得 负=扣减
    BalanceAfter    NUMBER         NOT NULL,
    ChangeType      VARCHAR2(30)   NOT NULL,      -- ORDER_EARN/REFUND_DEDUCT
    OrderId         NUMBER,
    CreatedAt       DATE           DEFAULT SYSDATE,
    CONSTRAINT FK_PointLog_Customer FOREIGN KEY (CustomerId) REFERENCES Crm_Customers(CustomerId)
);

-- 7. Biz_Orders - 订单主表
CREATE TABLE Biz_Orders (
    OrderId         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderNo         VARCHAR2(50)   NOT NULL UNIQUE,
    CustomerId      NUMBER         NOT NULL,
    PromoterId      NUMBER,
    AddressId       NUMBER         NOT NULL,
    ReceiverName    VARCHAR2(50)   NOT NULL,      -- 下单时收件人快照
    ReceiverPhone   VARCHAR2(20)   NOT NULL,      -- 下单时电话快照
    ShippingAddress VARCHAR2(500)  NOT NULL,      -- 下单时完整地址快照
    TotalAmount     NUMBER(10,2)   NOT NULL,
    DiscountAmount  NUMBER(10,2)   DEFAULT 0,
    FreightAmount   NUMBER(10,2)   DEFAULT 0,
    FinalAmount     NUMBER(10,2)   NOT NULL,
    CommBaseAmount  NUMBER(10,2),
    CommBonusAmount NUMBER(10,2),
    CommSettlementDate DATE,
    PointsEarned    NUMBER         DEFAULT 0,
    OrderStatus     NUMBER(2)      DEFAULT 0,     -- 0=待付 1=已付 2=已发货 3=完成 4=取消 5=退款中 6=已退款
    CreatedAt       DATE           DEFAULT SYSDATE,
    UpdatedAt       DATE,
    CONSTRAINT FK_Order_Customer FOREIGN KEY (CustomerId) REFERENCES Crm_Customers(CustomerId),
    CONSTRAINT FK_Order_Promoter  FOREIGN KEY (PromoterId)  REFERENCES Crm_Promoters(PromoterId),
    CONSTRAINT FK_Order_Address  FOREIGN KEY (AddressId)  REFERENCES Crm_UserAddresses(AddressId),
    CONSTRAINT CK_Order_Status CHECK (OrderStatus IN (0, 1, 2, 3, 4, 5, 6)),
    CONSTRAINT CK_Order_Amounts CHECK (
        TotalAmount >= 0
        AND DiscountAmount >= 0
        AND FreightAmount >= 0
        AND FinalAmount >= 0
    )
);

CREATE INDEX IX_Order_CustomerCreated
    ON Biz_Orders (CustomerId, CreatedAt);

CREATE INDEX IX_Order_StatusCreated
    ON Biz_Orders (OrderStatus, CreatedAt);

-- 8.1 Fin_PaymentRecords - 支付流水
CREATE TABLE Fin_PaymentRecords (
    PayId           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderId         NUMBER         NOT NULL,
    PayMethod       VARCHAR2(50),
    TransactionNo   VARCHAR2(100),
    PayAmount       NUMBER(10,2),
    Status          VARCHAR2(20)   NOT NULL,
    CreatedAt       DATE           DEFAULT SYSDATE,
    CONSTRAINT FK_Payment_Order FOREIGN KEY (OrderId) REFERENCES Biz_Orders(OrderId)
);

-- 8.2 Fin_Refunds - 退款记录
CREATE TABLE Fin_Refunds (
    RefundId        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderId         NUMBER         NOT NULL,
    PromoterId      NUMBER,
    RefundStatus    VARCHAR2(20),
    RefundAmount    NUMBER(10,2),
    CreatedAt       DATE           DEFAULT SYSDATE,
    CONSTRAINT FK_Refund_Order FOREIGN KEY (OrderId) REFERENCES Biz_Orders(OrderId)
);

-- 9. Log_AuditTrails - 操作审计日志
CREATE TABLE Log_AuditTrails (
    LogId           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TableName       VARCHAR2(50),
    ActionType      VARCHAR2(20),
    OldValue        VARCHAR2(1000),
    NewValue        VARCHAR2(1000),
    OperatorType    VARCHAR2(20),
    CreatedAt       DATE           DEFAULT SYSDATE
);

-- 8. Biz_OrderDetails - 订单明细
CREATE TABLE Biz_OrderDetails (
    OrderDetailId   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderId         NUMBER         NOT NULL,
    ProductId       NUMBER         NOT NULL,
    ProductName     VARCHAR2(200)  NOT NULL,
    Quantity        NUMBER         NOT NULL,
    UnitPrice       NUMBER(10,2)   NOT NULL,
    SubTotal        NUMBER(10,2)   NOT NULL,
    SupplierId      NUMBER,
    CONSTRAINT FK_Detail_Order FOREIGN KEY (OrderId) REFERENCES Biz_Orders(OrderId)
);
