-- 团长收款账户绑定：微信 / 支付宝 / 银行卡。已有列时跳过。
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE CRM_PROMOTERS ADD (WECHATACCOUNT VARCHAR2(100))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE CRM_PROMOTERS ADD (ALIPAYACCOUNT VARCHAR2(100))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE CRM_PROMOTERS ADD (BANKCARDACCOUNT VARCHAR2(100))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
