-- 团长-消费者多对多绑定表（当前仅两个属性，后续可再 ALTER 增加字段）
-- 库中已存在此表：CONSUMERID VARCHAR2(64)、PROMOTERID VARCHAR2(36)、联合主键 PK_CRM_PCR
CREATE TABLE CRM_PCR (
    CONSUMERID VARCHAR2(64) NOT NULL,
    PROMOTERID VARCHAR2(36) NOT NULL,
    CONSTRAINT PK_CRM_PCR PRIMARY KEY (CONSUMERID, PROMOTERID)
);
